; drm236_io.s -- PDP-6 Type 167 I/O Processor / Type 236 drum driver.
;
; One request transfers exactly one 128-word Type-236 physical block.  Before
; the process table exists, the service uses the JOSS-style polled sequence.
; At runtime a single DMA engine is serialized and completed by the two PI2
; indications generated by the Type 167 and Type 236 respectively.

        .text
        .globl  drm236_pi_handler
        .globl  drm236_read_block_service
        .globl  drm236_write_block_service
        .globl  drm236_active_request
        .globl  drm236_pending_request
        .globl  mfsdev_drm_reads
        .globl  mfsdev_drm_writes
        .globl  mfsdev_storage_errors
        .globl  pdp10_pi_dispatch_done
        .globl  kret_ok
        .globl  kret_neg1
        .globl  proc_table
        .globl  proc_wait_event
        .globl  storage_request_init
        .globl  proc_wakeup_event

        .set    DRM_DP_ERROR,0100060
        .set    DRM_DP_DONE,0000010
        .set    DRM_DR_DONE,0000100
        .set    DRM_DR_ERROR,0001000
        .set    DRM_DR_SELECT,0000260
        .set    DRM_DR_DESELECT,0000270
        .set    DRM_DR_CLEAR_DESELECT,0200270
        .set    DRM_DR_WRITE,0000220
        .set    DRM_DR_READ,0000230
        .set    DRM_PI_LEVEL,2
        .set    DRM_POLL_LIMIT,0777777
        .set    DRM_POLL_PASSES,010

; AC1 = Type-236 18-bit address, AC2 = core buffer.
drm236_read_block_service:
        setz    3,                      ; DP read: device -> core
        movei   4,DRM_DR_READ
        jrst    drm236_request

drm236_write_block_service:
        movei   3,0100                  ; DP write: core -> device
        movei   4,DRM_DR_WRITE

drm236_request:
        skipn   proc_table
        jrst    drm236_poll_request

        ; Runtime request descriptor on the caller's private kernel stack:
        ;   0: Type-236 address,,core buffer
        ;   1: Type-236 operation (READ or WRITE)
        ;   2: completion event (0 pending, 1 success, -1 failure)
        add     017,[3,,3]
        pushj   017,storage_request_init

drm236_runtime_retry:
        movei   1,-2(017)
        skipn   drm236_active_request
        jrst    drm236_runtime_claim

; Minimal assumption-free scheduler: retain exactly one pending request in the
; existing state word.  There is no rotational/timing model.  If the FIFO slot
; is occupied, wait for the active owner to complete and retry.  Slot 0 uses
; the same path: proc_wait_event polls there, while PI completion promotes the
; pending descriptor directly, so no scheduler wakeup is required for handoff.
drm236_runtime_queue:
        skipe   drm236_pending_request
        jrst    drm236_runtime_queue_full
        movem   1,drm236_pending_request
        ; Close the completion/enqueue race.  If the previous owner completed
        ; before seeing this pending pointer, claim the now-idle engine here.
        skipe   drm236_active_request
        jrst    drm236_runtime_wait
        setzm   drm236_pending_request
drm236_runtime_claim:
        movem   1,drm236_active_request
        pushj   017,drm236_start_active
drm236_runtime_wait:
        movei   1,(017)
        pushj   017,proc_wait_event
        jrst    drm236_runtime_finish

drm236_runtime_queue_full:
        skipn   1,drm236_active_request
        jrst    drm236_runtime_retry
        addi    1,2
        pushj   017,proc_wait_event
        jrst    drm236_runtime_retry

drm236_runtime_finish:
        move    1,(017)
        move    4,-1(017)               ; preserve operation for accounting
        sub     017,[3,,3]
        sojn    1,drm236_account_error
        jrst    drm236_account_success

; Start the stack descriptor named by AC1 using PI channel 2.
drm236_start_active:
        move    6,(1)
        move    4,1(1)                  ; READ/WRITE command
        hrrz    2,6                     ; core buffer
        hlrz    1,6                     ; Type-236 address
        setz    3,                      ; DP read: device -> core
        trnn    4,010                   ; READ 0230 has bit 010; WRITE 0220 does not
        movei   3,0100                  ; DP write: core -> device
        movei   5,DRM_PI_LEVEL
        jrst    drm236_start_hw

; Common Type-167/236 transfer start. AC1 address, AC2 buffer, AC3 DP
; direction, AC4 drum operation, AC5 PI bits (zero for polled boot I/O).
drm236_start_hw:
        cono    0010,0(3)
        move    6,[-0200,,0]
        hrr     6,2
        datao   0010,6
        datao   0400,1
        cono    0400,DRM_DR_SELECT
        add     4,5
        cono    0400,0(4)
        popj    017,

; PI2 receives two completions for a normal transfer.  Type 167 completion is
; acknowledged first; the later Type 236 completion publishes the result and
; wakes both the owner and any caller waiting for the one DMA engine.
drm236_pi_handler:
        coni    0010,1
        trne    1,DRM_DP_ERROR
        jrst    drm236_pi_error
        trne    1,DRM_DP_DONE
        jrst    drm236_pi_dp_done
        coni    0400,1
        trne    1,DRM_DR_ERROR
        jrst    drm236_pi_error
        trnn    1,DRM_DR_DONE
        jrst    pdp10_pi_dispatch_done
        cono    0400,DRM_DR_DESELECT
        movei   2,1
        jrst    drm236_pi_finish

drm236_pi_dp_done:
        cono    0010,0
        jrst    pdp10_pi_dispatch_done

drm236_pi_error:
        cono    0010,0
        cono    0400,DRM_DR_CLEAR_DESELECT
        seto    2,

drm236_pi_finish:
        skipn   1,drm236_active_request
        jrst    pdp10_pi_dispatch_done
        movem   2,2(1)
        setzm   drm236_active_request
        addi    1,2
        pushj   017,proc_wakeup_event
        skipn   1,drm236_pending_request
        jrst    pdp10_pi_dispatch_done
        setzm   drm236_pending_request
        movem   1,drm236_active_request
        pushj   017,drm236_start_active
        jrst    pdp10_pi_dispatch_done

; Early-boot polled path.  AC1 address, AC2 buffer, AC3 DP direction, AC4 DR op.
drm236_poll_request:
        setz    5,
        pushj   017,drm236_start_hw
        ; A Type-236 request may wait almost one full 8192-word revolution.
        ; Keep the inner counter 18-bit/PDP-6-friendly and repeat it enough
        ; times for simulator instruction-rate scaling as well as real hardware.
        movei   7,DRM_POLL_PASSES
drm236_poll_dp_outer:
        movei   5,DRM_POLL_LIMIT
drm236_poll_dp:
        coni    0010,6
        trne    6,DRM_DP_ERROR
        jrst    drm236_poll_error
        trne    6,DRM_DP_DONE
        jrst    drm236_poll_dp_done
        sojg    5,drm236_poll_dp
        sojg    7,drm236_poll_dp_outer
        jrst    drm236_poll_error

drm236_poll_dp_done:
        cono    0010,0
        movei   7,DRM_POLL_PASSES
drm236_poll_dr_outer:
        movei   5,DRM_POLL_LIMIT
drm236_poll_dr:
        coni    0400,6
        trne    6,DRM_DR_ERROR
        jrst    drm236_poll_error
        trne    6,DRM_DR_DONE
        jrst    drm236_poll_success
        sojg    5,drm236_poll_dr
        sojg    7,drm236_poll_dr_outer
        jrst    drm236_poll_error

drm236_poll_success:
        cono    0400,DRM_DR_DESELECT
        jrst    drm236_account_success

drm236_poll_error:
        cono    0010,0
        cono    0400,DRM_DR_CLEAR_DESELECT
        jrst    drm236_account_error

; DRM0 occupies MonitorFS device view id 021.  The dense counter slots also host the
; runtime ownership words in otherwise-unused ids 017/020, so extending the
; arrays through DRM0 costs no additional fixed KCORE.
drm236_account_success:
        trne    4,010                   ; READ 0230 has bit 010, WRITE 0220 does not
        aos     mfsdev_drm_reads
        trnn    4,010
        aos     mfsdev_drm_writes
        jrst    kret_ok

drm236_account_error:
        aos     mfsdev_storage_errors+5
        jrst    kret_neg1
