; drm236_io.s -- PDP-6 Type 167 I/O Processor / Type 236 drum driver.
;
; One request transfers exactly one 128-word Type-236 physical block.  Before
; the process table exists, the service uses the JOSS-style polled sequence.
; At runtime a single DMA engine is serialized and completed by the two PI2
; indications generated by the Type 167 and Type 236 respectively.

        .text
        .globl  drm236_pi_handler
        .globl  drm236_read_block_service
        .globl  drm236_write_block_service
        .globl  drm236_active_request
        .globl  drm236_idle_event
        .globl  devicefs_drm_reads
        .globl  devicefs_drm_writes
        .globl  devicefs_storage_errors
        .globl  pdp10_pi_dispatch_done
        .globl  pdp10_ret_ok
        .globl  pdp10_ret_neg1
        .globl  proc_table
        .globl  proc_wait_event
        .globl  proc_wakeup_event

        .set    DRM_DP_ERROR,0100060
        .set    DRM_DP_DONE,0000010
        .set    DRM_DR_DONE,0000100
        .set    DRM_DR_ERROR,0001000
        .set    DRM_DR_SELECT,0000260
        .set    DRM_DR_DESELECT,0000270
        .set    DRM_DR_CLEAR_DESELECT,0200270
        .set    DRM_DR_WRITE,0000220
        .set    DRM_DR_READ,0000230
        .set    DRM_PI_LEVEL,2
        .set    DRM_POLL_LIMIT,0777777

; AC1 = Type-236 18-bit address, AC2 = core buffer.
drm236_read_block_service:
        setz    3,                      ; DP read: device -> core
        movei   4,DRM_DR_READ
        jrst    drm236_request

drm236_write_block_service:
        movei   3,0100                  ; DP write: core -> device
        movei   4,DRM_DR_WRITE

drm236_request:
        skipn   proc_table
        jrst    drm236_poll_request

        ; Runtime request descriptor on the caller's private kernel stack:
        ;   0: Type-236 address,,core buffer
        ;   1: Type-236 operation (READ or WRITE)
        ;   2: completion event (0 pending, 1 success, -1 failure)
        hrlz    5,1
        hrr     5,2
        push    017,5
        push    017,4
        setz    5,
        push    017,5

drm236_runtime_retry:
        movei   1,-2(017)
        skipe   drm236_active_request
        jrst    drm236_runtime_busy
        movem   1,drm236_active_request
        pushj   017,drm236_start_active
        movei   1,(017)
        pushj   017,proc_wait_event
        move    1,(017)
        move    4,-1(017)               ; preserve operation for accounting
        sub     017,[3,,3]
        caie    1,1
        jrst    drm236_account_error
        jrst    drm236_account_success

; Close the active-request/completion race in the same way as the filesystem
; provider lock: clear the wait event first, then recheck ownership before
; sleeping.  An interrupt between the recheck and wait sets the event nonzero.
drm236_runtime_busy:
        setzm   drm236_idle_event
        skipn   drm236_active_request
        jrst    drm236_runtime_retry
        movei   1,drm236_idle_event
        pushj   017,proc_wait_event
        jrst    drm236_runtime_retry

; Start the stack descriptor named by AC1 using PI channel 2.
drm236_start_active:
        move    5,(1)
        hlrz    4,5                     ; Type-236 address
        hrrz    2,5                     ; core buffer
        move    5,1(1)                  ; READ/WRITE command
        caie    5,DRM_DR_WRITE
        jrst    drm236_start_read
        cono    0010,0100+DRM_PI_LEVEL
        jrst    drm236_start_dp
drm236_start_read:
        cono    0010,DRM_PI_LEVEL
drm236_start_dp:
        move    3,[-0200,,0]
        hrr     3,2
        datao   0010,3
        datao   0400,4
        cono    0400,DRM_DR_SELECT
        addi    5,DRM_PI_LEVEL
        cono    0400,0(5)
        popj    017,

; PI2 receives two completions for a normal transfer.  Type 167 completion is
; acknowledged first; the later Type 236 completion publishes the result and
; wakes both the owner and any caller waiting for the one DMA engine.
drm236_pi_handler:
        coni    0010,1
        trne    1,DRM_DP_ERROR
        jrst    drm236_pi_error
        trne    1,DRM_DP_DONE
        jrst    drm236_pi_dp_done
        coni    0400,1
        trne    1,DRM_DR_ERROR
        jrst    drm236_pi_error
        trnn    1,DRM_DR_DONE
        jrst    pdp10_pi_dispatch_done
        cono    0400,DRM_DR_DESELECT
        movei   2,1
        jrst    drm236_pi_finish

drm236_pi_dp_done:
        cono    0010,0
        jrst    pdp10_pi_dispatch_done

drm236_pi_error:
        cono    0010,0
        cono    0400,DRM_DR_CLEAR_DESELECT
        seto    2,

drm236_pi_finish:
        skipn   1,drm236_active_request
        jrst    pdp10_pi_dispatch_done
        movem   2,2(1)
        setzm   drm236_active_request
        setom   drm236_idle_event
        addi    1,2
        pushj   017,proc_wakeup_event
        movei   1,drm236_idle_event
        pushj   017,proc_wakeup_event
        jrst    pdp10_pi_dispatch_done

; Early-boot polled path.  AC1 address, AC2 buffer, AC3 DP direction, AC4 DR op.
drm236_poll_request:
        cono    0010,0(3)
        move    5,[-0200,,0]
        hrr     5,2
        datao   0010,5
        datao   0400,1
        cono    0400,DRM_DR_SELECT
        cono    0400,0(4)

        movei   5,DRM_POLL_LIMIT
drm236_poll_dp:
        coni    0010,6
        trne    6,DRM_DP_ERROR
        jrst    drm236_poll_error
        trne    6,DRM_DP_DONE
        jrst    drm236_poll_dp_done
        sojg    5,drm236_poll_dp
        jrst    drm236_poll_error

drm236_poll_dp_done:
        cono    0010,0
        movei   5,DRM_POLL_LIMIT
drm236_poll_dr:
        coni    0400,6
        trne    6,DRM_DR_ERROR
        jrst    drm236_poll_error
        trne    6,DRM_DR_DONE
        jrst    drm236_poll_success
        sojg    5,drm236_poll_dr
        jrst    drm236_poll_error

drm236_poll_success:
        cono    0400,DRM_DR_DESELECT
        jrst    drm236_account_success

drm236_poll_error:
        cono    0010,0
        cono    0400,DRM_DR_CLEAR_DESELECT
        jrst    drm236_account_error

; Keep DRM accounting sparse: DEVICEFS ids 017 and 020 have no ordinary I/O
; counters, so extending the legacy dense arrays through DRM0 would waste RAM.
drm236_account_success:
        caie    4,DRM_DR_WRITE
        jrst    drm236_account_read
        aos     devicefs_drm_writes
        jrst    pdp10_ret_ok
drm236_account_read:
        aos     devicefs_drm_reads
        jrst    pdp10_ret_ok

drm236_account_error:
        aos     devicefs_storage_errors+5
        jrst    pdp10_ret_neg1
